/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_EXTENSIONS_API_CAST_CHANNEL_PROTO_AUTHORITY_KEYS_PB_H_INCLUDED
#define PB_EXTENSIONS_API_CAST_CHANNEL_PROTO_AUTHORITY_KEYS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _extensions_api_cast_channel_proto_AuthorityKeys {
    pb_callback_t keys;
} extensions_api_cast_channel_proto_AuthorityKeys;

typedef struct _extensions_api_cast_channel_proto_AuthorityKeys_Key {
    pb_callback_t fingerprint;
    pb_callback_t public_key;
} extensions_api_cast_channel_proto_AuthorityKeys_Key;


/* Initializer values for message structs */
#define extensions_api_cast_channel_proto_AuthorityKeys_init_default {{{NULL}, NULL}}
#define extensions_api_cast_channel_proto_AuthorityKeys_Key_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define extensions_api_cast_channel_proto_AuthorityKeys_init_zero {{{NULL}, NULL}}
#define extensions_api_cast_channel_proto_AuthorityKeys_Key_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define extensions_api_cast_channel_proto_AuthorityKeys_keys_tag 1
#define extensions_api_cast_channel_proto_AuthorityKeys_Key_fingerprint_tag 1
#define extensions_api_cast_channel_proto_AuthorityKeys_Key_public_key_tag 2

/* Struct field encoding specification for nanopb */
#define extensions_api_cast_channel_proto_AuthorityKeys_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  keys,              1)
#define extensions_api_cast_channel_proto_AuthorityKeys_CALLBACK pb_default_field_callback
#define extensions_api_cast_channel_proto_AuthorityKeys_DEFAULT NULL
#define extensions_api_cast_channel_proto_AuthorityKeys_keys_MSGTYPE extensions_api_cast_channel_proto_AuthorityKeys_Key

#define extensions_api_cast_channel_proto_AuthorityKeys_Key_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    fingerprint,       1) \
X(a, CALLBACK, REQUIRED, BYTES,    public_key,        2)
#define extensions_api_cast_channel_proto_AuthorityKeys_Key_CALLBACK pb_default_field_callback
#define extensions_api_cast_channel_proto_AuthorityKeys_Key_DEFAULT NULL

extern const pb_msgdesc_t extensions_api_cast_channel_proto_AuthorityKeys_msg;
extern const pb_msgdesc_t extensions_api_cast_channel_proto_AuthorityKeys_Key_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define extensions_api_cast_channel_proto_AuthorityKeys_fields &extensions_api_cast_channel_proto_AuthorityKeys_msg
#define extensions_api_cast_channel_proto_AuthorityKeys_Key_fields &extensions_api_cast_channel_proto_AuthorityKeys_Key_msg

/* Maximum encoded size of messages (where known) */
/* extensions_api_cast_channel_proto_AuthorityKeys_size depends on runtime parameters */
/* extensions_api_cast_channel_proto_AuthorityKeys_Key_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
