/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "authority_keys.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(extensions_api_cast_channel_proto_AuthorityKeys, extensions_api_cast_channel_proto_AuthorityKeys, AUTO)


PB_BIND(extensions_api_cast_channel_proto_AuthorityKeys_Key, extensions_api_cast_channel_proto_AuthorityKeys_Key, AUTO)



