/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_EXTENSIONS_API_CAST_CHANNEL_PROTO_LOGGING_PB_H_INCLUDED
#define PB_EXTENSIONS_API_CAST_CHANNEL_PROTO_LOGGING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _extensions_api_cast_channel_proto_EventType {
    extensions_api_cast_channel_proto_EventType_EVENT_TYPE_UNKNOWN = 0,
    extensions_api_cast_channel_proto_EventType_CAST_SOCKET_CREATED = 1,
    extensions_api_cast_channel_proto_EventType_READY_STATE_CHANGED = 2,
    extensions_api_cast_channel_proto_EventType_CONNECTION_STATE_CHANGED = 3,
    extensions_api_cast_channel_proto_EventType_READ_STATE_CHANGED = 4,
    extensions_api_cast_channel_proto_EventType_WRITE_STATE_CHANGED = 5,
    extensions_api_cast_channel_proto_EventType_ERROR_STATE_CHANGED = 6,
    extensions_api_cast_channel_proto_EventType_CONNECT_FAILED = 7,
    extensions_api_cast_channel_proto_EventType_TCP_SOCKET_CONNECT = 8,
    extensions_api_cast_channel_proto_EventType_TCP_SOCKET_SET_KEEP_ALIVE = 9,
    extensions_api_cast_channel_proto_EventType_SSL_CERT_WHITELISTED = 10,
    extensions_api_cast_channel_proto_EventType_SSL_SOCKET_CONNECT = 11,
    extensions_api_cast_channel_proto_EventType_SSL_INFO_OBTAINED = 12,
    extensions_api_cast_channel_proto_EventType_DER_ENCODED_CERT_OBTAIN = 13,
    extensions_api_cast_channel_proto_EventType_RECEIVED_CHALLENGE_REPLY = 14,
    extensions_api_cast_channel_proto_EventType_AUTH_CHALLENGE_REPLY = 15,
    extensions_api_cast_channel_proto_EventType_CONNECT_TIMED_OUT = 16,
    extensions_api_cast_channel_proto_EventType_SEND_MESSAGE_FAILED = 17,
    extensions_api_cast_channel_proto_EventType_MESSAGE_ENQUEUED = 18,
    extensions_api_cast_channel_proto_EventType_SOCKET_WRITE = 19,
    extensions_api_cast_channel_proto_EventType_MESSAGE_WRITTEN = 20,
    extensions_api_cast_channel_proto_EventType_SOCKET_READ = 21,
    extensions_api_cast_channel_proto_EventType_MESSAGE_READ = 22,
    extensions_api_cast_channel_proto_EventType_SOCKET_CLOSED = 25,
    extensions_api_cast_channel_proto_EventType_SSL_CERT_EXCESSIVE_LIFETIME = 26,
    extensions_api_cast_channel_proto_EventType_CHANNEL_POLICY_ENFORCED = 27,
    extensions_api_cast_channel_proto_EventType_TCP_SOCKET_CONNECT_COMPLETE = 28,
    extensions_api_cast_channel_proto_EventType_SSL_SOCKET_CONNECT_COMPLETE = 29,
    extensions_api_cast_channel_proto_EventType_SSL_SOCKET_CONNECT_FAILED = 30,
    extensions_api_cast_channel_proto_EventType_SEND_AUTH_CHALLENGE_FAILED = 31,
    extensions_api_cast_channel_proto_EventType_AUTH_CHALLENGE_REPLY_INVALID = 32,
    extensions_api_cast_channel_proto_EventType_PING_WRITE_ERROR = 33
} extensions_api_cast_channel_proto_EventType;

typedef enum _extensions_api_cast_channel_proto_ChannelAuth {
    extensions_api_cast_channel_proto_ChannelAuth_SSL = 1,
    extensions_api_cast_channel_proto_ChannelAuth_SSL_VERIFIED = 2
} extensions_api_cast_channel_proto_ChannelAuth;

typedef enum _extensions_api_cast_channel_proto_ReadyState {
    extensions_api_cast_channel_proto_ReadyState_READY_STATE_NONE = 1,
    extensions_api_cast_channel_proto_ReadyState_READY_STATE_CONNECTING = 2,
    extensions_api_cast_channel_proto_ReadyState_READY_STATE_OPEN = 3,
    extensions_api_cast_channel_proto_ReadyState_READY_STATE_CLOSING = 4,
    extensions_api_cast_channel_proto_ReadyState_READY_STATE_CLOSED = 5
} extensions_api_cast_channel_proto_ReadyState;

typedef enum _extensions_api_cast_channel_proto_ConnectionState {
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_UNKNOWN = 1,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_TCP_CONNECT = 2,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_TCP_CONNECT_COMPLETE = 3,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_SSL_CONNECT = 4,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_SSL_CONNECT_COMPLETE = 5,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_AUTH_CHALLENGE_SEND = 6,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_AUTH_CHALLENGE_SEND_COMPLETE = 7,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_AUTH_CHALLENGE_REPLY_COMPLETE = 8,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_START_CONNECT = 9,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_FINISHED = 100,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_ERROR = 101,
    extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_TIMEOUT = 102
} extensions_api_cast_channel_proto_ConnectionState;

typedef enum _extensions_api_cast_channel_proto_ReadState {
    extensions_api_cast_channel_proto_ReadState_READ_STATE_UNKNOWN = 1,
    extensions_api_cast_channel_proto_ReadState_READ_STATE_READ = 2,
    extensions_api_cast_channel_proto_ReadState_READ_STATE_READ_COMPLETE = 3,
    extensions_api_cast_channel_proto_ReadState_READ_STATE_DO_CALLBACK = 4,
    extensions_api_cast_channel_proto_ReadState_READ_STATE_HANDLE_ERROR = 5,
    extensions_api_cast_channel_proto_ReadState_READ_STATE_ERROR = 100
} extensions_api_cast_channel_proto_ReadState;

typedef enum _extensions_api_cast_channel_proto_WriteState {
    extensions_api_cast_channel_proto_WriteState_WRITE_STATE_UNKNOWN = 1,
    extensions_api_cast_channel_proto_WriteState_WRITE_STATE_WRITE = 2,
    extensions_api_cast_channel_proto_WriteState_WRITE_STATE_WRITE_COMPLETE = 3,
    extensions_api_cast_channel_proto_WriteState_WRITE_STATE_DO_CALLBACK = 4,
    extensions_api_cast_channel_proto_WriteState_WRITE_STATE_HANDLE_ERROR = 5,
    extensions_api_cast_channel_proto_WriteState_WRITE_STATE_ERROR = 100,
    extensions_api_cast_channel_proto_WriteState_WRITE_STATE_IDLE = 101
} extensions_api_cast_channel_proto_WriteState;

typedef enum _extensions_api_cast_channel_proto_ErrorState {
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_NONE = 1,
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_CHANNEL_NOT_OPEN = 2,
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_AUTHENTICATION_ERROR = 3,
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_CONNECT_ERROR = 4,
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_SOCKET_ERROR = 5,
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_TRANSPORT_ERROR = 6,
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_INVALID_MESSAGE = 7,
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_INVALID_CHANNEL_ID = 8,
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_CONNECT_TIMEOUT = 9,
    extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_UNKNOWN = 10
} extensions_api_cast_channel_proto_ErrorState;

typedef enum _extensions_api_cast_channel_proto_ChallengeReplyErrorType {
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_NONE = 1,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_PEER_CERT_EMPTY = 2,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_WRONG_PAYLOAD_TYPE = 3,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_NO_PAYLOAD = 4,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_PAYLOAD_PARSING_FAILED = 5,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_MESSAGE_ERROR = 6,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_NO_RESPONSE = 7,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_FINGERPRINT_NOT_FOUND = 8,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_CERT_PARSING_FAILED = 9,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_CERT_NOT_SIGNED_BY_TRUSTED_CA = 10,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_CANNOT_EXTRACT_PUBLIC_KEY = 11,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_SIGNED_BLOBS_MISMATCH = 12,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_TLS_CERT_VALIDITY_PERIOD_TOO_LONG = 13,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_TLS_CERT_VALID_START_DATE_IN_FUTURE = 14,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_TLS_CERT_EXPIRED = 15,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_CRL_INVALID = 16,
    extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_CERT_REVOKED = 17
} extensions_api_cast_channel_proto_ChallengeReplyErrorType;

/* Struct definitions */
typedef struct _extensions_api_cast_channel_proto_AggregatedSocketEvent {
    bool has_id;
    int32_t id;
    bool has_endpoint_id;
    int32_t endpoint_id;
    bool has_channel_auth_type;
    extensions_api_cast_channel_proto_ChannelAuth channel_auth_type;
    pb_callback_t socket_event;
    bool has_bytes_read;
    int64_t bytes_read;
    bool has_bytes_written;
    int64_t bytes_written;
} extensions_api_cast_channel_proto_AggregatedSocketEvent;

typedef struct _extensions_api_cast_channel_proto_Log {
    pb_callback_t aggregated_socket_event;
    bool has_num_evicted_aggregated_socket_events;
    int32_t num_evicted_aggregated_socket_events;
    bool has_num_evicted_socket_events;
    int32_t num_evicted_socket_events;
} extensions_api_cast_channel_proto_Log;

typedef struct _extensions_api_cast_channel_proto_SocketEvent {
    bool has_type;
    extensions_api_cast_channel_proto_EventType type;
    bool has_timestamp_micros;
    int64_t timestamp_micros;
    pb_callback_t details;
    bool has_net_return_value;
    int32_t net_return_value;
    pb_callback_t message_namespace;
    bool has_ready_state;
    extensions_api_cast_channel_proto_ReadyState ready_state;
    bool has_connection_state;
    extensions_api_cast_channel_proto_ConnectionState connection_state;
    bool has_read_state;
    extensions_api_cast_channel_proto_ReadState read_state;
    bool has_write_state;
    extensions_api_cast_channel_proto_WriteState write_state;
    bool has_error_state;
    extensions_api_cast_channel_proto_ErrorState error_state;
    bool has_challenge_reply_error_type;
    extensions_api_cast_channel_proto_ChallengeReplyErrorType challenge_reply_error_type;
    bool has_nss_error_code;
    int32_t nss_error_code;
} extensions_api_cast_channel_proto_SocketEvent;


/* Helper constants for enums */
#define _extensions_api_cast_channel_proto_EventType_MIN extensions_api_cast_channel_proto_EventType_EVENT_TYPE_UNKNOWN
#define _extensions_api_cast_channel_proto_EventType_MAX extensions_api_cast_channel_proto_EventType_PING_WRITE_ERROR
#define _extensions_api_cast_channel_proto_EventType_ARRAYSIZE ((extensions_api_cast_channel_proto_EventType)(extensions_api_cast_channel_proto_EventType_PING_WRITE_ERROR+1))

#define _extensions_api_cast_channel_proto_ChannelAuth_MIN extensions_api_cast_channel_proto_ChannelAuth_SSL
#define _extensions_api_cast_channel_proto_ChannelAuth_MAX extensions_api_cast_channel_proto_ChannelAuth_SSL_VERIFIED
#define _extensions_api_cast_channel_proto_ChannelAuth_ARRAYSIZE ((extensions_api_cast_channel_proto_ChannelAuth)(extensions_api_cast_channel_proto_ChannelAuth_SSL_VERIFIED+1))

#define _extensions_api_cast_channel_proto_ReadyState_MIN extensions_api_cast_channel_proto_ReadyState_READY_STATE_NONE
#define _extensions_api_cast_channel_proto_ReadyState_MAX extensions_api_cast_channel_proto_ReadyState_READY_STATE_CLOSED
#define _extensions_api_cast_channel_proto_ReadyState_ARRAYSIZE ((extensions_api_cast_channel_proto_ReadyState)(extensions_api_cast_channel_proto_ReadyState_READY_STATE_CLOSED+1))

#define _extensions_api_cast_channel_proto_ConnectionState_MIN extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_UNKNOWN
#define _extensions_api_cast_channel_proto_ConnectionState_MAX extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_TIMEOUT
#define _extensions_api_cast_channel_proto_ConnectionState_ARRAYSIZE ((extensions_api_cast_channel_proto_ConnectionState)(extensions_api_cast_channel_proto_ConnectionState_CONN_STATE_TIMEOUT+1))

#define _extensions_api_cast_channel_proto_ReadState_MIN extensions_api_cast_channel_proto_ReadState_READ_STATE_UNKNOWN
#define _extensions_api_cast_channel_proto_ReadState_MAX extensions_api_cast_channel_proto_ReadState_READ_STATE_ERROR
#define _extensions_api_cast_channel_proto_ReadState_ARRAYSIZE ((extensions_api_cast_channel_proto_ReadState)(extensions_api_cast_channel_proto_ReadState_READ_STATE_ERROR+1))

#define _extensions_api_cast_channel_proto_WriteState_MIN extensions_api_cast_channel_proto_WriteState_WRITE_STATE_UNKNOWN
#define _extensions_api_cast_channel_proto_WriteState_MAX extensions_api_cast_channel_proto_WriteState_WRITE_STATE_IDLE
#define _extensions_api_cast_channel_proto_WriteState_ARRAYSIZE ((extensions_api_cast_channel_proto_WriteState)(extensions_api_cast_channel_proto_WriteState_WRITE_STATE_IDLE+1))

#define _extensions_api_cast_channel_proto_ErrorState_MIN extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_NONE
#define _extensions_api_cast_channel_proto_ErrorState_MAX extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_UNKNOWN
#define _extensions_api_cast_channel_proto_ErrorState_ARRAYSIZE ((extensions_api_cast_channel_proto_ErrorState)(extensions_api_cast_channel_proto_ErrorState_CHANNEL_ERROR_UNKNOWN+1))

#define _extensions_api_cast_channel_proto_ChallengeReplyErrorType_MIN extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_NONE
#define _extensions_api_cast_channel_proto_ChallengeReplyErrorType_MAX extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_CERT_REVOKED
#define _extensions_api_cast_channel_proto_ChallengeReplyErrorType_ARRAYSIZE ((extensions_api_cast_channel_proto_ChallengeReplyErrorType)(extensions_api_cast_channel_proto_ChallengeReplyErrorType_CHALLENGE_REPLY_ERROR_CERT_REVOKED+1))


/* Initializer values for message structs */
#define extensions_api_cast_channel_proto_SocketEvent_init_default {false, _extensions_api_cast_channel_proto_EventType_MIN, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, _extensions_api_cast_channel_proto_ReadyState_MIN, false, _extensions_api_cast_channel_proto_ConnectionState_MIN, false, _extensions_api_cast_channel_proto_ReadState_MIN, false, _extensions_api_cast_channel_proto_WriteState_MIN, false, _extensions_api_cast_channel_proto_ErrorState_MIN, false, _extensions_api_cast_channel_proto_ChallengeReplyErrorType_MIN, false, 0}
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_init_default {false, 0, false, 0, false, _extensions_api_cast_channel_proto_ChannelAuth_MIN, {{NULL}, NULL}, false, 0, false, 0}
#define extensions_api_cast_channel_proto_Log_init_default {{{NULL}, NULL}, false, 0, false, 0}
#define extensions_api_cast_channel_proto_SocketEvent_init_zero {false, _extensions_api_cast_channel_proto_EventType_MIN, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, _extensions_api_cast_channel_proto_ReadyState_MIN, false, _extensions_api_cast_channel_proto_ConnectionState_MIN, false, _extensions_api_cast_channel_proto_ReadState_MIN, false, _extensions_api_cast_channel_proto_WriteState_MIN, false, _extensions_api_cast_channel_proto_ErrorState_MIN, false, _extensions_api_cast_channel_proto_ChallengeReplyErrorType_MIN, false, 0}
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_init_zero {false, 0, false, 0, false, _extensions_api_cast_channel_proto_ChannelAuth_MIN, {{NULL}, NULL}, false, 0, false, 0}
#define extensions_api_cast_channel_proto_Log_init_zero {{{NULL}, NULL}, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_id_tag 1
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_endpoint_id_tag 2
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_channel_auth_type_tag 3
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_socket_event_tag 4
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_bytes_read_tag 5
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_bytes_written_tag 6
#define extensions_api_cast_channel_proto_Log_aggregated_socket_event_tag 1
#define extensions_api_cast_channel_proto_Log_num_evicted_aggregated_socket_events_tag 2
#define extensions_api_cast_channel_proto_Log_num_evicted_socket_events_tag 3
#define extensions_api_cast_channel_proto_SocketEvent_type_tag 1
#define extensions_api_cast_channel_proto_SocketEvent_timestamp_micros_tag 2
#define extensions_api_cast_channel_proto_SocketEvent_details_tag 3
#define extensions_api_cast_channel_proto_SocketEvent_net_return_value_tag 4
#define extensions_api_cast_channel_proto_SocketEvent_message_namespace_tag 5
#define extensions_api_cast_channel_proto_SocketEvent_ready_state_tag 6
#define extensions_api_cast_channel_proto_SocketEvent_connection_state_tag 7
#define extensions_api_cast_channel_proto_SocketEvent_read_state_tag 8
#define extensions_api_cast_channel_proto_SocketEvent_write_state_tag 9
#define extensions_api_cast_channel_proto_SocketEvent_error_state_tag 10
#define extensions_api_cast_channel_proto_SocketEvent_challenge_reply_error_type_tag 11
#define extensions_api_cast_channel_proto_SocketEvent_nss_error_code_tag 12

/* Struct field encoding specification for nanopb */
#define extensions_api_cast_channel_proto_SocketEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, INT64,    timestamp_micros,   2) \
X(a, CALLBACK, OPTIONAL, STRING,   details,           3) \
X(a, STATIC,   OPTIONAL, INT32,    net_return_value,   4) \
X(a, CALLBACK, OPTIONAL, STRING,   message_namespace,   5) \
X(a, STATIC,   OPTIONAL, UENUM,    ready_state,       6) \
X(a, STATIC,   OPTIONAL, UENUM,    connection_state,   7) \
X(a, STATIC,   OPTIONAL, UENUM,    read_state,        8) \
X(a, STATIC,   OPTIONAL, UENUM,    write_state,       9) \
X(a, STATIC,   OPTIONAL, UENUM,    error_state,      10) \
X(a, STATIC,   OPTIONAL, UENUM,    challenge_reply_error_type,  11) \
X(a, STATIC,   OPTIONAL, INT32,    nss_error_code,   12)
#define extensions_api_cast_channel_proto_SocketEvent_CALLBACK pb_default_field_callback
#define extensions_api_cast_channel_proto_SocketEvent_DEFAULT (const pb_byte_t*)"\x30\x01\x38\x01\x40\x01\x48\x01\x50\x01\x58\x01\x00"

#define extensions_api_cast_channel_proto_AggregatedSocketEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    id,                1) \
X(a, STATIC,   OPTIONAL, INT32,    endpoint_id,       2) \
X(a, STATIC,   OPTIONAL, UENUM,    channel_auth_type,   3) \
X(a, CALLBACK, REPEATED, MESSAGE,  socket_event,      4) \
X(a, STATIC,   OPTIONAL, INT64,    bytes_read,        5) \
X(a, STATIC,   OPTIONAL, INT64,    bytes_written,     6)
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_CALLBACK pb_default_field_callback
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_DEFAULT (const pb_byte_t*)"\x18\x01\x00"
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_socket_event_MSGTYPE extensions_api_cast_channel_proto_SocketEvent

#define extensions_api_cast_channel_proto_Log_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  aggregated_socket_event,   1) \
X(a, STATIC,   OPTIONAL, INT32,    num_evicted_aggregated_socket_events,   2) \
X(a, STATIC,   OPTIONAL, INT32,    num_evicted_socket_events,   3)
#define extensions_api_cast_channel_proto_Log_CALLBACK pb_default_field_callback
#define extensions_api_cast_channel_proto_Log_DEFAULT NULL
#define extensions_api_cast_channel_proto_Log_aggregated_socket_event_MSGTYPE extensions_api_cast_channel_proto_AggregatedSocketEvent

extern const pb_msgdesc_t extensions_api_cast_channel_proto_SocketEvent_msg;
extern const pb_msgdesc_t extensions_api_cast_channel_proto_AggregatedSocketEvent_msg;
extern const pb_msgdesc_t extensions_api_cast_channel_proto_Log_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define extensions_api_cast_channel_proto_SocketEvent_fields &extensions_api_cast_channel_proto_SocketEvent_msg
#define extensions_api_cast_channel_proto_AggregatedSocketEvent_fields &extensions_api_cast_channel_proto_AggregatedSocketEvent_msg
#define extensions_api_cast_channel_proto_Log_fields &extensions_api_cast_channel_proto_Log_msg

/* Maximum encoded size of messages (where known) */
/* extensions_api_cast_channel_proto_SocketEvent_size depends on runtime parameters */
/* extensions_api_cast_channel_proto_AggregatedSocketEvent_size depends on runtime parameters */
/* extensions_api_cast_channel_proto_Log_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
