/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "logging.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(extensions_api_cast_channel_proto_SocketEvent, extensions_api_cast_channel_proto_SocketEvent, AUTO)


PB_BIND(extensions_api_cast_channel_proto_AggregatedSocketEvent, extensions_api_cast_channel_proto_AggregatedSocketEvent, AUTO)


PB_BIND(extensions_api_cast_channel_proto_Log, extensions_api_cast_channel_proto_Log, AUTO)











